[package]

name = "glium_renderer"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]

[dependencies]
nalgebra = "*"
glium = "*"
glutin = "*"
glium_text = "*"

[dependencies.ui]
path = ".."
